#![allow(dead_code)]
#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]
pub const SYS__SYSCTL: usize = 156;
pub const SYS_ACCEPT: usize = 43;
pub const SYS_ACCEPT4: usize = 288;
pub const SYS_ACCESS: usize = 21;
pub const SYS_ACCT: usize = 163;
pub const SYS_ADD_KEY: usize = 248;
pub const SYS_ADJTIMEX: usize = 159;
pub const SYS_AFS_SYSCALL: usize = 183;
pub const SYS_ALARM: usize = 37;
pub const SYS_ARCH_PRCTL: usize = 158;
pub const SYS_BIND: usize = 49;
pub const SYS_BPF: usize = 321;
pub const SYS_BRK: usize = 12;
pub const SYS_CAPGET: usize = 125;
pub const SYS_CAPSET: usize = 126;
pub const SYS_CHDIR: usize = 80;
pub const SYS_CHMOD: usize = 90;
pub const SYS_CHOWN: usize = 92;
pub const SYS_CHROOT: usize = 161;
pub const SYS_CLOCK_ADJTIME: usize = 305;
pub const SYS_CLOCK_GETRES: usize = 229;
pub const SYS_CLOCK_GETTIME: usize = 228;
pub const SYS_CLOCK_NANOSLEEP: usize = 230;
pub const SYS_CLOCK_SETTIME: usize = 227;
pub const SYS_CLONE: usize = 56;
pub const SYS_CLONE3: usize = 435;
pub const SYS_CLOSE: usize = 3;
pub const SYS_CLOSE_RANGE: usize = 436;
pub const SYS_CONNECT: usize = 42;
pub const SYS_COPY_FILE_RANGE: usize = 326;
pub const SYS_CREAT: usize = 85;
pub const SYS_CREATE_MODULE: usize = 174;
pub const SYS_DELETE_MODULE: usize = 176;
pub const SYS_DUP: usize = 32;
pub const SYS_DUP2: usize = 33;
pub const SYS_DUP3: usize = 292;
pub const SYS_EPOLL_CREATE: usize = 213;
pub const SYS_EPOLL_CREATE1: usize = 291;
pub const SYS_EPOLL_CTL: usize = 233;
pub const SYS_EPOLL_CTL_OLD: usize = 214;
pub const SYS_EPOLL_PWAIT: usize = 281;
pub const SYS_EPOLL_PWAIT2: usize = 441;
pub const SYS_EPOLL_WAIT: usize = 232;
pub const SYS_EPOLL_WAIT_OLD: usize = 215;
pub const SYS_EVENTFD: usize = 284;
pub const SYS_EVENTFD2: usize = 290;
pub const SYS_EXECVE: usize = 59;
pub const SYS_EXECVEAT: usize = 322;
pub const SYS_EXIT: usize = 60;
pub const SYS_EXIT_GROUP: usize = 231;
pub const SYS_FACCESSAT: usize = 269;
pub const SYS_FACCESSAT2: usize = 439;
pub const SYS_FADVISE64: usize = 221;
pub const SYS_FALLOCATE: usize = 285;
pub const SYS_FANOTIFY_INIT: usize = 300;
pub const SYS_FANOTIFY_MARK: usize = 301;
pub const SYS_FCHDIR: usize = 81;
pub const SYS_FCHMOD: usize = 91;
pub const SYS_FCHMODAT: usize = 268;
pub const SYS_FCHOWN: usize = 93;
pub const SYS_FCHOWNAT: usize = 260;
pub const SYS_FCNTL: usize = 72;
pub const SYS_FDATASYNC: usize = 75;
pub const SYS_FGETXATTR: usize = 193;
pub const SYS_FINIT_MODULE: usize = 313;
pub const SYS_FLISTXATTR: usize = 196;
pub const SYS_FLOCK: usize = 73;
pub const SYS_FORK: usize = 57;
pub const SYS_FREMOVEXATTR: usize = 199;
pub const SYS_FSCONFIG: usize = 431;
pub const SYS_FSETXATTR: usize = 190;
pub const SYS_FSMOUNT: usize = 432;
pub const SYS_FSOPEN: usize = 430;
pub const SYS_FSPICK: usize = 433;
pub const SYS_FSTAT: usize = 5;
pub const SYS_FSTATFS: usize = 138;
pub const SYS_FSYNC: usize = 74;
pub const SYS_FTRUNCATE: usize = 77;
pub const SYS_FUTEX: usize = 202;
pub const SYS_FUTIMESAT: usize = 261;
pub const SYS_GET_KERNEL_SYMS: usize = 177;
pub const SYS_GET_MEMPOLICY: usize = 239;
pub const SYS_GET_ROBUST_LIST: usize = 274;
pub const SYS_GET_THREAD_AREA: usize = 211;
pub const SYS_GETCPU: usize = 309;
pub const SYS_GETCWD: usize = 79;
pub const SYS_GETDENTS: usize = 78;
pub const SYS_GETDENTS64: usize = 217;
pub const SYS_GETEGID: usize = 108;
pub const SYS_GETEUID: usize = 107;
pub const SYS_GETGID: usize = 104;
pub const SYS_GETGROUPS: usize = 115;
pub const SYS_GETITIMER: usize = 36;
pub const SYS_GETPEERNAME: usize = 52;
pub const SYS_GETPGID: usize = 121;
pub const SYS_GETPGRP: usize = 111;
pub const SYS_GETPID: usize = 39;
pub const SYS_GETPMSG: usize = 181;
pub const SYS_GETPPID: usize = 110;
pub const SYS_GETPRIORITY: usize = 140;
pub const SYS_GETRANDOM: usize = 318;
pub const SYS_GETRESGID: usize = 120;
pub const SYS_GETRESUID: usize = 118;
pub const SYS_GETRLIMIT: usize = 97;
pub const SYS_GETRUSAGE: usize = 98;
pub const SYS_GETSID: usize = 124;
pub const SYS_GETSOCKNAME: usize = 51;
pub const SYS_GETSOCKOPT: usize = 55;
pub const SYS_GETTID: usize = 186;
pub const SYS_GETTIMEOFDAY: usize = 96;
pub const SYS_GETUID: usize = 102;
pub const SYS_GETXATTR: usize = 191;
pub const SYS_INIT_MODULE: usize = 175;
pub const SYS_INOTIFY_ADD_WATCH: usize = 254;
pub const SYS_INOTIFY_INIT: usize = 253;
pub const SYS_INOTIFY_INIT1: usize = 294;
pub const SYS_INOTIFY_RM_WATCH: usize = 255;
pub const SYS_IO_CANCEL: usize = 210;
pub const SYS_IO_DESTROY: usize = 207;
pub const SYS_IO_GETEVENTS: usize = 208;
pub const SYS_IO_PGETEVENTS: usize = 333;
pub const SYS_IO_SETUP: usize = 206;
pub const SYS_IO_SUBMIT: usize = 209;
pub const SYS_IO_URING_ENTER: usize = 426;
pub const SYS_IO_URING_REGISTER: usize = 427;
pub const SYS_IO_URING_SETUP: usize = 425;
pub const SYS_IOCTL: usize = 16;
pub const SYS_IOPERM: usize = 173;
pub const SYS_IOPL: usize = 172;
pub const SYS_IOPRIO_GET: usize = 252;
pub const SYS_IOPRIO_SET: usize = 251;
pub const SYS_KCMP: usize = 312;
pub const SYS_KEXEC_FILE_LOAD: usize = 320;
pub const SYS_KEXEC_LOAD: usize = 246;
pub const SYS_KEYCTL: usize = 250;
pub const SYS_KILL: usize = 62;
pub const SYS_LCHOWN: usize = 94;
pub const SYS_LGETXATTR: usize = 192;
pub const SYS_LINK: usize = 86;
pub const SYS_LINKAT: usize = 265;
pub const SYS_LISTEN: usize = 50;
pub const SYS_LISTXATTR: usize = 194;
pub const SYS_LLISTXATTR: usize = 195;
pub const SYS_LOOKUP_DCOOKIE: usize = 212;
pub const SYS_LREMOVEXATTR: usize = 198;
pub const SYS_LSEEK: usize = 8;
pub const SYS_LSETXATTR: usize = 189;
pub const SYS_LSTAT: usize = 6;
pub const SYS_MADVISE: usize = 28;
pub const SYS_MBIND: usize = 237;
pub const SYS_MEMBARRIER: usize = 324;
pub const SYS_MEMFD_CREATE: usize = 319;
pub const SYS_MIGRATE_PAGES: usize = 256;
pub const SYS_MINCORE: usize = 27;
pub const SYS_MKDIR: usize = 83;
pub const SYS_MKDIRAT: usize = 258;
pub const SYS_MKNOD: usize = 133;
pub const SYS_MKNODAT: usize = 259;
pub const SYS_MLOCK: usize = 149;
pub const SYS_MLOCK2: usize = 325;
pub const SYS_MLOCKALL: usize = 151;
pub const SYS_MMAP: usize = 9;
pub const SYS_MODIFY_LDT: usize = 154;
pub const SYS_MOUNT: usize = 165;
pub const SYS_MOUNT_SETATTR: usize = 442;
pub const SYS_MOVE_MOUNT: usize = 429;
pub const SYS_MOVE_PAGES: usize = 279;
pub const SYS_MPROTECT: usize = 10;
pub const SYS_MQ_GETSETATTR: usize = 245;
pub const SYS_MQ_NOTIFY: usize = 244;
pub const SYS_MQ_OPEN: usize = 240;
pub const SYS_MQ_TIMEDRECEIVE: usize = 243;
pub const SYS_MQ_TIMEDSEND: usize = 242;
pub const SYS_MQ_UNLINK: usize = 241;
pub const SYS_MREMAP: usize = 25;
pub const SYS_MSGCTL: usize = 71;
pub const SYS_MSGGET: usize = 68;
pub const SYS_MSGRCV: usize = 70;
pub const SYS_MSGSND: usize = 69;
pub const SYS_MSYNC: usize = 26;
pub const SYS_MUNLOCK: usize = 150;
pub const SYS_MUNLOCKALL: usize = 152;
pub const SYS_MUNMAP: usize = 11;
pub const SYS_NAME_TO_HANDLE_AT: usize = 303;
pub const SYS_NANOSLEEP: usize = 35;
pub const SYS_NEWFSTATAT: usize = 262;
pub const SYS_NFSSERVCTL: usize = 180;
pub const SYS_OPEN: usize = 2;
pub const SYS_OPEN_BY_HANDLE_AT: usize = 304;
pub const SYS_OPEN_TREE: usize = 428;
pub const SYS_OPENAT: usize = 257;
pub const SYS_OPENAT2: usize = 437;
pub const SYS_PAUSE: usize = 34;
pub const SYS_PERF_EVENT_OPEN: usize = 298;
pub const SYS_PERSONALITY: usize = 135;
pub const SYS_PIDFD_GETFD: usize = 438;
pub const SYS_PIDFD_OPEN: usize = 434;
pub const SYS_PIDFD_SEND_SIGNAL: usize = 424;
pub const SYS_PIPE: usize = 22;
pub const SYS_PIPE2: usize = 293;
pub const SYS_PIVOT_ROOT: usize = 155;
pub const SYS_PKEY_ALLOC: usize = 330;
pub const SYS_PKEY_FREE: usize = 331;
pub const SYS_PKEY_MPROTECT: usize = 329;
pub const SYS_POLL: usize = 7;
pub const SYS_PPOLL: usize = 271;
pub const SYS_PRCTL: usize = 157;
pub const SYS_PREAD64: usize = 17;
pub const SYS_PREADV: usize = 295;
pub const SYS_PREADV2: usize = 327;
pub const SYS_PRLIMIT64: usize = 302;
pub const SYS_PROCESS_MADVISE: usize = 440;
pub const SYS_PROCESS_VM_READV: usize = 310;
pub const SYS_PROCESS_VM_WRITEV: usize = 311;
pub const SYS_PSELECT6: usize = 270;
pub const SYS_PTRACE: usize = 101;
pub const SYS_PUTPMSG: usize = 182;
pub const SYS_PWRITE64: usize = 18;
pub const SYS_PWRITEV: usize = 296;
pub const SYS_PWRITEV2: usize = 328;
pub const SYS_QUERY_MODULE: usize = 178;
pub const SYS_QUOTACTL: usize = 179;
pub const SYS_READ: usize = 0;
pub const SYS_READAHEAD: usize = 187;
pub const SYS_READLINK: usize = 89;
pub const SYS_READLINKAT: usize = 267;
pub const SYS_READV: usize = 19;
pub const SYS_REBOOT: usize = 169;
pub const SYS_RECVFROM: usize = 45;
pub const SYS_RECVMMSG: usize = 299;
pub const SYS_RECVMSG: usize = 47;
pub const SYS_REMAP_FILE_PAGES: usize = 216;
pub const SYS_REMOVEXATTR: usize = 197;
pub const SYS_RENAME: usize = 82;
pub const SYS_RENAMEAT: usize = 264;
pub const SYS_RENAMEAT2: usize = 316;
pub const SYS_REQUEST_KEY: usize = 249;
pub const SYS_RESTART_SYSCALL: usize = 219;
pub const SYS_RMDIR: usize = 84;
pub const SYS_RSEQ: usize = 334;
pub const SYS_RT_SIGACTION: usize = 13;
pub const SYS_RT_SIGPENDING: usize = 127;
pub const SYS_RT_SIGPROCMASK: usize = 14;
pub const SYS_RT_SIGQUEUEINFO: usize = 129;
pub const SYS_RT_SIGRETURN: usize = 15;
pub const SYS_RT_SIGSUSPEND: usize = 130;
pub const SYS_RT_SIGTIMEDWAIT: usize = 128;
pub const SYS_RT_TGSIGQUEUEINFO: usize = 297;
pub const SYS_SCHED_GET_PRIORITY_MAX: usize = 146;
pub const SYS_SCHED_GET_PRIORITY_MIN: usize = 147;
pub const SYS_SCHED_GETAFFINITY: usize = 204;
pub const SYS_SCHED_GETATTR: usize = 315;
pub const SYS_SCHED_GETPARAM: usize = 143;
pub const SYS_SCHED_GETSCHEDULER: usize = 145;
pub const SYS_SCHED_RR_GET_INTERVAL: usize = 148;
pub const SYS_SCHED_SETAFFINITY: usize = 203;
pub const SYS_SCHED_SETATTR: usize = 314;
pub const SYS_SCHED_SETPARAM: usize = 142;
pub const SYS_SCHED_SETSCHEDULER: usize = 144;
pub const SYS_SCHED_YIELD: usize = 24;
pub const SYS_SECCOMP: usize = 317;
pub const SYS_SECURITY: usize = 185;
pub const SYS_SELECT: usize = 23;
pub const SYS_SEMCTL: usize = 66;
pub const SYS_SEMGET: usize = 64;
pub const SYS_SEMOP: usize = 65;
pub const SYS_SEMTIMEDOP: usize = 220;
pub const SYS_SENDFILE: usize = 40;
pub const SYS_SENDMMSG: usize = 307;
pub const SYS_SENDMSG: usize = 46;
pub const SYS_SENDTO: usize = 44;
pub const SYS_SET_MEMPOLICY: usize = 238;
pub const SYS_SET_ROBUST_LIST: usize = 273;
pub const SYS_SET_THREAD_AREA: usize = 205;
pub const SYS_SET_TID_ADDRESS: usize = 218;
pub const SYS_SETDOMAINNAME: usize = 171;
pub const SYS_SETFSGID: usize = 123;
pub const SYS_SETFSUID: usize = 122;
pub const SYS_SETGID: usize = 106;
pub const SYS_SETGROUPS: usize = 116;
pub const SYS_SETHOSTNAME: usize = 170;
pub const SYS_SETITIMER: usize = 38;
pub const SYS_SETNS: usize = 308;
pub const SYS_SETPGID: usize = 109;
pub const SYS_SETPRIORITY: usize = 141;
pub const SYS_SETREGID: usize = 114;
pub const SYS_SETRESGID: usize = 119;
pub const SYS_SETRESUID: usize = 117;
pub const SYS_SETREUID: usize = 113;
pub const SYS_SETRLIMIT: usize = 160;
pub const SYS_SETSID: usize = 112;
pub const SYS_SETSOCKOPT: usize = 54;
pub const SYS_SETTIMEOFDAY: usize = 164;
pub const SYS_SETUID: usize = 105;
pub const SYS_SETXATTR: usize = 188;
pub const SYS_SHMAT: usize = 30;
pub const SYS_SHMCTL: usize = 31;
pub const SYS_SHMDT: usize = 67;
pub const SYS_SHMGET: usize = 29;
pub const SYS_SHUTDOWN: usize = 48;
pub const SYS_SIGALTSTACK: usize = 131;
pub const SYS_SIGNALFD: usize = 282;
pub const SYS_SIGNALFD4: usize = 289;
pub const SYS_SOCKET: usize = 41;
pub const SYS_SOCKETPAIR: usize = 53;
pub const SYS_SPLICE: usize = 275;
pub const SYS_STAT: usize = 4;
pub const SYS_STATFS: usize = 137;
pub const SYS_STATX: usize = 332;
pub const SYS_SWAPOFF: usize = 168;
pub const SYS_SWAPON: usize = 167;
pub const SYS_SYMLINK: usize = 88;
pub const SYS_SYMLINKAT: usize = 266;
pub const SYS_SYNC: usize = 162;
pub const SYS_SYNC_FILE_RANGE: usize = 277;
pub const SYS_SYNCFS: usize = 306;
pub const SYS_SYSFS: usize = 139;
pub const SYS_SYSINFO: usize = 99;
pub const SYS_SYSLOG: usize = 103;
pub const SYS_TEE: usize = 276;
pub const SYS_TGKILL: usize = 234;
pub const SYS_TIME: usize = 201;
pub const SYS_TIMER_CREATE: usize = 222;
pub const SYS_TIMER_DELETE: usize = 226;
pub const SYS_TIMER_GETOVERRUN: usize = 225;
pub const SYS_TIMER_GETTIME: usize = 224;
pub const SYS_TIMER_SETTIME: usize = 223;
pub const SYS_TIMERFD_CREATE: usize = 283;
pub const SYS_TIMERFD_GETTIME: usize = 287;
pub const SYS_TIMERFD_SETTIME: usize = 286;
pub const SYS_TIMES: usize = 100;
pub const SYS_TKILL: usize = 200;
pub const SYS_TRUNCATE: usize = 76;
pub const SYS_TUXCALL: usize = 184;
pub const SYS_UMASK: usize = 95;
pub const SYS_UMOUNT2: usize = 166;
pub const SYS_UNAME: usize = 63;
pub const SYS_UNLINK: usize = 87;
pub const SYS_UNLINKAT: usize = 263;
pub const SYS_UNSHARE: usize = 272;
pub const SYS_USELIB: usize = 134;
pub const SYS_USERFAULTFD: usize = 323;
pub const SYS_USTAT: usize = 136;
pub const SYS_UTIME: usize = 132;
pub const SYS_UTIMENSAT: usize = 280;
pub const SYS_UTIMES: usize = 235;
pub const SYS_VFORK: usize = 58;
pub const SYS_VHANGUP: usize = 153;
pub const SYS_VMSPLICE: usize = 278;
pub const SYS_VSERVER: usize = 236;
pub const SYS_WAIT4: usize = 61;
pub const SYS_WAITID: usize = 247;
pub const SYS_WRITE: usize = 1;
pub const SYS_WRITEV: usize = 20;

use num_traits::{FromPrimitive, ToPrimitive};
use system_error::SystemError;
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, FromPrimitive, ToPrimitive, PartialEq, Eq)]
pub enum SysCall {
    SYS__SYSCTL = 156,
    SYS_ACCEPT = 43,
    SYS_ACCEPT4 = 288,
    SYS_ACCESS = 21,
    SYS_ACCT = 163,
    SYS_ADD_KEY = 248,
    SYS_ADJTIMEX = 159,
    SYS_AFS_SYSCALL = 183,
    SYS_ALARM = 37,
    SYS_ARCH_PRCTL = 158,
    SYS_BIND = 49,
    SYS_BPF = 321,
    SYS_BRK = 12,
    SYS_CAPGET = 125,
    SYS_CAPSET = 126,
    SYS_CHDIR = 80,
    SYS_CHMOD = 90,
    SYS_CHOWN = 92,
    SYS_CHROOT = 161,
    SYS_CLOCK_ADJTIME = 305,
    SYS_CLOCK_GETRES = 229,
    SYS_CLOCK_GETTIME = 228,
    SYS_CLOCK_NANOSLEEP = 230,
    SYS_CLOCK_SETTIME = 227,
    SYS_CLONE = 56,
    SYS_CLONE3 = 435,
    SYS_CLOSE = 3,
    SYS_CLOSE_RANGE = 436,
    SYS_CONNECT = 42,
    SYS_COPY_FILE_RANGE = 326,
    SYS_CREAT = 85,
    SYS_CREATE_MODULE = 174,
    SYS_DELETE_MODULE = 176,
    SYS_DUP = 32,
    SYS_DUP2 = 33,
    SYS_DUP3 = 292,
    SYS_EPOLL_CREATE = 213,
    SYS_EPOLL_CREATE1 = 291,
    SYS_EPOLL_CTL = 233,
    SYS_EPOLL_CTL_OLD = 214,
    SYS_EPOLL_PWAIT = 281,
    SYS_EPOLL_PWAIT2 = 441,
    SYS_EPOLL_WAIT = 232,
    SYS_EPOLL_WAIT_OLD = 215,
    SYS_EVENTFD = 284,
    SYS_EVENTFD2 = 290,
    SYS_EXECVE = 59,
    SYS_EXECVEAT = 322,
    SYS_EXIT = 60,
    SYS_EXIT_GROUP = 231,
    SYS_FACCESSAT = 269,
    SYS_FACCESSAT2 = 439,
    SYS_FADVISE64 = 221,
    SYS_FALLOCATE = 285,
    SYS_FANOTIFY_INIT = 300,
    SYS_FANOTIFY_MARK = 301,
    SYS_FCHDIR = 81,
    SYS_FCHMOD = 91,
    SYS_FCHMODAT = 268,
    SYS_FCHOWN = 93,
    SYS_FCHOWNAT = 260,
    SYS_FCNTL = 72,
    SYS_FDATASYNC = 75,
    SYS_FGETXATTR = 193,
    SYS_FINIT_MODULE = 313,
    SYS_FLISTXATTR = 196,
    SYS_FLOCK = 73,
    SYS_FORK = 57,
    SYS_FREMOVEXATTR = 199,
    SYS_FSCONFIG = 431,
    SYS_FSETXATTR = 190,
    SYS_FSMOUNT = 432,
    SYS_FSOPEN = 430,
    SYS_FSPICK = 433,
    SYS_FSTAT = 5,
    SYS_FSTATFS = 138,
    SYS_FSYNC = 74,
    SYS_FTRUNCATE = 77,
    SYS_FUTEX = 202,
    SYS_FUTIMESAT = 261,
    SYS_GET_KERNEL_SYMS = 177,
    SYS_GET_MEMPOLICY = 239,
    SYS_GET_ROBUST_LIST = 274,
    SYS_GET_THREAD_AREA = 211,
    SYS_GETCPU = 309,
    SYS_GETCWD = 79,
    SYS_GETDENTS = 78,
    SYS_GETDENTS64 = 217,
    SYS_GETEGID = 108,
    SYS_GETEUID = 107,
    SYS_GETGID = 104,
    SYS_GETGROUPS = 115,
    SYS_GETITIMER = 36,
    SYS_GETPEERNAME = 52,
    SYS_GETPGID = 121,
    SYS_GETPGRP = 111,
    SYS_GETPID = 39,
    SYS_GETPMSG = 181,
    SYS_GETPPID = 110,
    SYS_GETPRIORITY = 140,
    SYS_GETRANDOM = 318,
    SYS_GETRESGID = 120,
    SYS_GETRESUID = 118,
    SYS_GETRLIMIT = 97,
    SYS_GETRUSAGE = 98,
    SYS_GETSID = 124,
    SYS_GETSOCKNAME = 51,
    SYS_GETSOCKOPT = 55,
    SYS_GETTID = 186,
    SYS_GETTIMEOFDAY = 96,
    SYS_GETUID = 102,
    SYS_GETXATTR = 191,
    SYS_INIT_MODULE = 175,
    SYS_INOTIFY_ADD_WATCH = 254,
    SYS_INOTIFY_INIT = 253,
    SYS_INOTIFY_INIT1 = 294,
    SYS_INOTIFY_RM_WATCH = 255,
    SYS_IO_CANCEL = 210,
    SYS_IO_DESTROY = 207,
    SYS_IO_GETEVENTS = 208,
    SYS_IO_PGETEVENTS = 333,
    SYS_IO_SETUP = 206,
    SYS_IO_SUBMIT = 209,
    SYS_IO_URING_ENTER = 426,
    SYS_IO_URING_REGISTER = 427,
    SYS_IO_URING_SETUP = 425,
    SYS_IOCTL = 16,
    SYS_IOPERM = 173,
    SYS_IOPL = 172,
    SYS_IOPRIO_GET = 252,
    SYS_IOPRIO_SET = 251,
    SYS_KCMP = 312,
    SYS_KEXEC_FILE_LOAD = 320,
    SYS_KEXEC_LOAD = 246,
    SYS_KEYCTL = 250,
    SYS_KILL = 62,
    SYS_LCHOWN = 94,
    SYS_LGETXATTR = 192,
    SYS_LINK = 86,
    SYS_LINKAT = 265,
    SYS_LISTEN = 50,
    SYS_LISTXATTR = 194,
    SYS_LLISTXATTR = 195,
    SYS_LOOKUP_DCOOKIE = 212,
    SYS_LREMOVEXATTR = 198,
    SYS_LSEEK = 8,
    SYS_LSETXATTR = 189,
    SYS_LSTAT = 6,
    SYS_MADVISE = 28,
    SYS_MBIND = 237,
    SYS_MEMBARRIER = 324,
    SYS_MEMFD_CREATE = 319,
    SYS_MIGRATE_PAGES = 256,
    SYS_MINCORE = 27,
    SYS_MKDIR = 83,
    SYS_MKDIRAT = 258,
    SYS_MKNOD = 133,
    SYS_MKNODAT = 259,
    SYS_MLOCK = 149,
    SYS_MLOCK2 = 325,
    SYS_MLOCKALL = 151,
    SYS_MMAP = 9,
    SYS_MODIFY_LDT = 154,
    SYS_MOUNT = 165,
    SYS_MOUNT_SETATTR = 442,
    SYS_MOVE_MOUNT = 429,
    SYS_MOVE_PAGES = 279,
    SYS_MPROTECT = 10,
    SYS_MQ_GETSETATTR = 245,
    SYS_MQ_NOTIFY = 244,
    SYS_MQ_OPEN = 240,
    SYS_MQ_TIMEDRECEIVE = 243,
    SYS_MQ_TIMEDSEND = 242,
    SYS_MQ_UNLINK = 241,
    SYS_MREMAP = 25,
    SYS_MSGCTL = 71,
    SYS_MSGGET = 68,
    SYS_MSGRCV = 70,
    SYS_MSGSND = 69,
    SYS_MSYNC = 26,
    SYS_MUNLOCK = 150,
    SYS_MUNLOCKALL = 152,
    SYS_MUNMAP = 11,
    SYS_NAME_TO_HANDLE_AT = 303,
    SYS_NANOSLEEP = 35,
    SYS_NEWFSTATAT = 262,
    SYS_NFSSERVCTL = 180,
    SYS_OPEN = 2,
    SYS_OPEN_BY_HANDLE_AT = 304,
    SYS_OPEN_TREE = 428,
    SYS_OPENAT = 257,
    SYS_OPENAT2 = 437,
    SYS_PAUSE = 34,
    SYS_PERF_EVENT_OPEN = 298,
    SYS_PERSONALITY = 135,
    SYS_PIDFD_GETFD = 438,
    SYS_PIDFD_OPEN = 434,
    SYS_PIDFD_SEND_SIGNAL = 424,
    SYS_PIPE = 22,
    SYS_PIPE2 = 293,
    SYS_PIVOT_ROOT = 155,
    SYS_PKEY_ALLOC = 330,
    SYS_PKEY_FREE = 331,
    SYS_PKEY_MPROTECT = 329,
    SYS_POLL = 7,
    SYS_PPOLL = 271,
    SYS_PRCTL = 157,
    SYS_PREAD64 = 17,
    SYS_PREADV = 295,
    SYS_PREADV2 = 327,
    SYS_PRLIMIT64 = 302,
    SYS_PROCESS_MADVISE = 440,
    SYS_PROCESS_VM_READV = 310,
    SYS_PROCESS_VM_WRITEV = 311,
    SYS_PSELECT6 = 270,
    SYS_PTRACE = 101,
    SYS_PUTPMSG = 182,
    SYS_PWRITE64 = 18,
    SYS_PWRITEV = 296,
    SYS_PWRITEV2 = 328,
    SYS_QUERY_MODULE = 178,
    SYS_QUOTACTL = 179,
    SYS_READ = 0,
    SYS_READAHEAD = 187,
    SYS_READLINK = 89,
    SYS_READLINKAT = 267,
    SYS_READV = 19,
    SYS_REBOOT = 169,
    SYS_RECVFROM = 45,
    SYS_RECVMMSG = 299,
    SYS_RECVMSG = 47,
    SYS_REMAP_FILE_PAGES = 216,
    SYS_REMOVEXATTR = 197,
    SYS_RENAME = 82,
    SYS_RENAMEAT = 264,
    SYS_RENAMEAT2 = 316,
    SYS_REQUEST_KEY = 249,
    SYS_RESTART_SYSCALL = 219,
    SYS_RMDIR = 84,
    SYS_RSEQ = 334,
    SYS_RT_SIGACTION = 13,
    SYS_RT_SIGPENDING = 127,
    SYS_RT_SIGPROCMASK = 14,
    SYS_RT_SIGQUEUEINFO = 129,
    SYS_RT_SIGRETURN = 15,
    SYS_RT_SIGSUSPEND = 130,
    SYS_RT_SIGTIMEDWAIT = 128,
    SYS_RT_TGSIGQUEUEINFO = 297,
    SYS_SCHED_GET_PRIORITY_MAX = 146,
    SYS_SCHED_GET_PRIORITY_MIN = 147,
    SYS_SCHED_GETAFFINITY = 204,
    SYS_SCHED_GETATTR = 315,
    SYS_SCHED_GETPARAM = 143,
    SYS_SCHED_GETSCHEDULER = 145,
    SYS_SCHED_RR_GET_INTERVAL = 148,
    SYS_SCHED_SETAFFINITY = 203,
    SYS_SCHED_SETATTR = 314,
    SYS_SCHED_SETPARAM = 142,
    SYS_SCHED_SETSCHEDULER = 144,
    SYS_SCHED_YIELD = 24,
    SYS_SECCOMP = 317,
    SYS_SECURITY = 185,
    SYS_SELECT = 23,
    SYS_SEMCTL = 66,
    SYS_SEMGET = 64,
    SYS_SEMOP = 65,
    SYS_SEMTIMEDOP = 220,
    SYS_SENDFILE = 40,
    SYS_SENDMMSG = 307,
    SYS_SENDMSG = 46,
    SYS_SENDTO = 44,
    SYS_SET_MEMPOLICY = 238,
    SYS_SET_ROBUST_LIST = 273,
    SYS_SET_THREAD_AREA = 205,
    SYS_SET_TID_ADDRESS = 218,
    SYS_SETDOMAINNAME = 171,
    SYS_SETFSGID = 123,
    SYS_SETFSUID = 122,
    SYS_SETGID = 106,
    SYS_SETGROUPS = 116,
    SYS_SETHOSTNAME = 170,
    SYS_SETITIMER = 38,
    SYS_SETNS = 308,
    SYS_SETPGID = 109,
    SYS_SETPRIORITY = 141,
    SYS_SETREGID = 114,
    SYS_SETRESGID = 119,
    SYS_SETRESUID = 117,
    SYS_SETREUID = 113,
    SYS_SETRLIMIT = 160,
    SYS_SETSID = 112,
    SYS_SETSOCKOPT = 54,
    SYS_SETTIMEOFDAY = 164,
    SYS_SETUID = 105,
    SYS_SETXATTR = 188,
    SYS_SHMAT = 30,
    SYS_SHMCTL = 31,
    SYS_SHMDT = 67,
    SYS_SHMGET = 29,
    SYS_SHUTDOWN = 48,
    SYS_SIGALTSTACK = 131,
    SYS_SIGNALFD = 282,
    SYS_SIGNALFD4 = 289,
    SYS_SOCKET = 41,
    SYS_SOCKETPAIR = 53,
    SYS_SPLICE = 275,
    SYS_STAT = 4,
    SYS_STATFS = 137,
    SYS_STATX = 332,
    SYS_SWAPOFF = 168,
    SYS_SWAPON = 167,
    SYS_SYMLINK = 88,
    SYS_SYMLINKAT = 266,
    SYS_SYNC = 162,
    SYS_SYNC_FILE_RANGE = 277,
    SYS_SYNCFS = 306,
    SYS_SYSFS = 139,
    SYS_SYSINFO = 99,
    SYS_SYSLOG = 103,
    SYS_TEE = 276,
    SYS_TGKILL = 234,
    SYS_TIME = 201,
    SYS_TIMER_CREATE = 222,
    SYS_TIMER_DELETE = 226,
    SYS_TIMER_GETOVERRUN = 225,
    SYS_TIMER_GETTIME = 224,
    SYS_TIMER_SETTIME = 223,
    SYS_TIMERFD_CREATE = 283,
    SYS_TIMERFD_GETTIME = 287,
    SYS_TIMERFD_SETTIME = 286,
    SYS_TIMES = 100,
    SYS_TKILL = 200,
    SYS_TRUNCATE = 76,
    SYS_TUXCALL = 184,
    SYS_UMASK = 95,
    SYS_UMOUNT2 = 166,
    SYS_UNAME = 63,
    SYS_UNLINK = 87,
    SYS_UNLINKAT = 263,
    SYS_UNSHARE = 272,
    SYS_USELIB = 134,
    SYS_USERFAULTFD = 323,
    SYS_USTAT = 136,
    SYS_UTIME = 132,
    SYS_UTIMENSAT = 280,
    SYS_UTIMES = 235,
    SYS_VFORK = 58,
    SYS_VHANGUP = 153,
    SYS_VMSPLICE = 278,
    SYS_VSERVER = 236,
    SYS_WAIT4 = 61,
    SYS_WAITID = 247,
    SYS_WRITE = 1,
    SYS_WRITEV = 20,
}

impl TryFrom<usize> for SysCall {
    type Error = SystemError;

    fn try_from(value: usize) -> Result<Self, Self::Error> {
        match <Self as FromPrimitive>::from_usize(value) {
            Some(p) => Ok(p),
            None => Err(SystemError::EINVAL),
        }
    }
}

impl From<SysCall> for usize {
    fn from(value: SysCall) -> Self {
        <SysCall as ToPrimitive>::to_usize(&value).unwrap()
    }
}
