name: Bug report
description: 创建bug报告以帮助我们改进
title: "[BUG] "
labels: bug
assignees: fslongjin

body: 
   - type: markdown 
     id: bug-info 
     attributes: 
       value: "## Bug Infomation" 
   - type: textarea 
     id: bug-main 
     validations: 
       required: true 
     attributes: 
       label: "描述错误" 
       description: "清晰而简明地描述错误是什么。" 
   - type: textarea 
     id: env-info 
     validations: 
       required: true 
     attributes: 
       label: "请填写您的电脑的信息" 
       description: "- 操作系统及版本：[例如，Ubuntu 22.04]
- DragonOS版本：[版本号或git提交哈希值]
- DADK版本：[通过`dadk --version`获取]
- Rust版本：[在DragonOS目录下使用`rustc --version`获取]" 
   - type: textarea 
     id: bug-step 
     validations: 
       required: true 
     attributes: 
       label: "重现步骤" 
       description: "重现行为的步骤：
1. 前往“...” \
2. 点击“...” \
3. 滚动到“...” \
4. 看到错误" 
   - type: textarea 
     id: feature-main 
     validations: 
       required: true 
     attributes: 
       label: "期望行为" 
       description: "清晰而简明地描述您期望发生什么。" 
   - type: textarea 
     id: bug-screenshot 
     validations: 
       required: false 
     attributes: 
       label: "屏幕截图" 
       description: "如果适用，添加屏幕截图以帮助解释您的问题。" 
   - type: textarea 
     id: other-info 
     validations: 
       required: false 
     attributes: 
       label: "其他上下文" 
       description: "在此处添加有关问题的任何其他上下文。" 
   - type: textarea 
     id: sys-log 
     validations: 
       required: true 
     attributes: 
       label: "系统日志" 
       description: "请附上出现bug时，项目目录下`serial_opt.txt`的日志信息." 
