name: 请求新功能
description: 为本项目提供一个新的功能/修改建议
title: ''
labels: enhancement
assignees: fslongjin

  - type: textarea 
    id: feature-main
    validations:
      required: true
    attributes:
      label: "您的功能请求是否与问题/故障有关？请描述一下。"
      description: "清晰而简明地描述问题是什么。例如：我总是感到沮丧，因为[...]"

  - type: textarea 
     id: feature-solution 
     validations: 
       required: true 
     attributes:
       label: "描述您想要的解决方案"
       description: "清晰而简明地描述您希望发生什么。"

  - type: textarea 
     id: feature-describe 
     validations: 
       required: true 
     attributes:
       label: "描述您考虑过的备选方案"
       description: "清晰而简明地描述您考虑过的任何备选解决方案或功能。"

  - type: textarea 
     id: feature-extra 
     validations: 
       required: false 
     attributes:
       label: "其他上下文"
       description: "在此处添加有关功能请求的任何其他上下文或截图。"
