[package]
name = "kernel_build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = "0.61.0"
lazy_static = "1.4.0"
cc = { version = "1.0.83", features = ["parallel"] }
toml = "0.8.6"