[package]
name = "test_symlink"
version = "0.1.0"
edition = "2021"
description = "测试symlink"
authors = [ "zky" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]