[package]
name = "get_pcb_info"
version = "0.1.0"
edition = "2021"
description = "获取进程的信息"
authors = [ "sparkzky <sparkhhhhhhhhhh@outlook.com>" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc="0.2"