all: shell.o cmd.o cmd_help.o

shell.o: shell.c
	gcc $(CFLAGS) -c shell.c  -o shell.o

cmd.o: cmd.c
	gcc $(CFLAGS) -c cmd.c  -o cmd.o

cmd_help.o: cmd_help.c
	gcc $(CFLAGS) -c cmd_help.c  -o cmd_help.o
