

CFLAGS += -I .

all: fabs.o round.o pow.o

fabs.o: fabs.c
	$(CC) $(CFLAGS) -c fabs.c -o fabs.o

round.o: round.c
	$(CC) $(CFLAGS) -c round.c -o round.o

pow.o: pow.c
	$(CC) $(CFLAGS) -c pow.c -o pow.o