[package]
name = "test_ps"
version = "0.1.0"
edition = "2021"
description = "一个简单的procps"
authors = [ "donjuanplatinum <donjuan@lecturify.net>" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]