#!/bin/sh
export PATH=/bin:/usr/bin:/usr/local/bin
# 设置 PS1 环境变量，定义彩色命令行提示符
# \\e[32m 设置绿色，\\e[34m 设置蓝色，\\e[0m 重置颜色，不可见字符必须用 \[ ... \] 包裹
# \\u 用户名，\\h 主机名，\\w 当前工作目录
export PS1='\[\e[32m\]\u\[\e[0m\]@\h:\[\e[34m\]\w\[\e[0m\]\$ '
trap ' ' INT