name: install-apt-packages

runs:
  using: composite
  steps:
      
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: llvm-dev libclang-dev clang gcc-multilib libssl-dev pkg-config
          version: ${{ hashFiles('.github/actions/install-apt-packages/action.yml') }}
      
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages:  gcc-riscv64-unknown-elf gcc-riscv64-linux-gnu gdb-multiarch
          version: ${{ hashFiles('.github/actions/install-apt-packages/action.yml') }}
    