# DADK 总控文件

[metadata]
# Target architecture. Options: x86_64, riscv64
arch = "riscv64"

# Builer version, affect the behavior of image generation
# Options: v1, v2
# Default: v1, to be compatible with the old version
builder-version = "v2"

# Hypervisor config path
hypervisor-config = "config/hypervisor.toml"

# RootFS config path
rootfs-config = "config/rootfs.toml"

# Boot config path
boot-config = "config/boot.toml"

# System root directory folder (DADK will copy the files in this directory to the root directory of the disk image)
sysroot-dir = "bin/riscv64/sysroot"

# DADK Root Cache directory path
cache-root-dir = "bin/riscv64/dadk_cache"

# User configuration directory path
# 这个字段只是临时用于兼容旧版本，v0.2版本重构完成后会删除
user-config-dir = "user/dadk/config"
