name: Build current version docs

on:
  pull_request:
    branches: [ "master" ]
    # paths:
    #   - 'docs/**'

env:
    GITHUB_REPOSITORY: ${{ github.repository }}
    GITHUB_REF: ${{ github.ref }}

jobs:

  build-current-version:
    if: github.repository == 'DragonOS-Community/DragonOS'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: install requirements
      working-directory: ./docs
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install -r requirements.txt

    - name: build docs
      working-directory: ./docs
      shell: bash -ileo pipefail {0}

      run: |
        make html
