name: Build multiversion docs

on:
  push:
    branches: [ "master" ]
    tags: [ "v*", "V*"]

env:
    GITHUB_REPOSITORY: ${{ github.repository }}
    GITHUB_REF: ${{ github.ref }}

jobs:

  build-multiversion:
    if: github.repository == 'DragonOS-Community/DragonOS'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: master
      
    - name: install requirements
      working-directory: ./docs
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install -r requirements.txt

    - name: build docs
      working-directory: ./docs
      shell: bash -ileo pipefail {0}

      run: |
        make html-multiversion
