name: Build current version docs

on:
  pull_request:
    branches: [ "master" ]

env:
    GITHUB_REPOSITORY: ${{ github.repository }}
    GITHUB_REF: ${{ github.ref }}

jobs:

  build-current-version:
    if: github.repository == 'DragonOS-Community/DragonOS'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: '22.11.0'
        cache: npm
        cache-dependency-path: docs/package-lock.json

    - name: install and build
      working-directory: ./docs
      run: |
        npm ci
        npm run docs:build
