name: Build multiversion docs

on:
  push:
    branches: [ "master" ]
    tags: [ "v*", "V*"]

env:
    GITHUB_REPOSITORY: ${{ github.repository }}
    GITHUB_REF: ${{ github.ref }}

jobs:

  build-multiversion:
    if: github.repository == 'DragonOS-Community/DragonOS'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: master

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: '22.11.0'
        cache: npm
        cache-dependency-path: docs/package-lock.json

    - name: install and build
      working-directory: ./docs
      run: |
        npm ci
        npm run docs:build

    - name: deploy docs to EdgeOne
      env:
        EDGEONE_API_TOKEN: ${{ secrets.EDGEONE_API_TOKEN }}
      run: |
        npx --yes edgeone makers deploy ./docs/.vitepress/dist -n dragonos-official-docs -t "${EDGEONE_API_TOKEN}" -e production
