name: Build multiversion docs

on:
  push:
    branches: [ "master" ]
    tags: [ "v*", "V*"]

env:
    GITHUB_REPOSITORY: ${{ github.repository }}
    GITHUB_REF: ${{ github.ref }}

jobs:

  build-multiversion:
    if: github.repository == 'DragonOS-Community/DragonOS'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: master

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: '22.11.0'
      
    - name: install requirements
      working-directory: ./docs
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools
        pip3 install -r requirements.txt

    - name: build docs
      working-directory: ./docs
      shell: bash -ileo pipefail {0}

      run: |
        make html-multiversion

    - name: deploy docs to EdgeOne
      env:
        EDGEONE_API_TOKEN: ${{ secrets.EDGEONE_API_TOKEN }}
      
      run: |
        npx --yes edgeone makers deploy ./docs/_build/html -n dragonos-official-docs -t "${EDGEONE_API_TOKEN}" -e production
