name: Rust format check

on: [push, pull_request]

jobs:
    # ensure the toolchain is cached
    ensure-toolchain:
        uses: ./.github/workflows/cache-toolchain.yml
  
    fmt:
        name: check
        runs-on: ubuntu-latest
        needs: [ensure-toolchain]
        steps:
            - uses: actions/checkout@v3
            - name: Cache build tools
              id: cache-build-tools
              uses: actions/cache@v3
              env:
                  cache-name: cache-build-tools
                  dadk_version: 0.1.2
              with:
                path: |
                  ~/.cargo
                  ~/.rustup
                  ~/.bashrc
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.dadk_version }}-${{ hashFiles('.github/workflows/cache-toolchain.yml') }}
    
            # 准备 bindings.rs
            # 由于 bindings.rs 是在 build.rs 中生成的，而这里为了方便，直接 touch 一个空文件
            - name: prepare bindings
              run: |
                    printf "\n" >> kernel/src/include/bindings/bindings.rs
                    printf "\n" >> user/libs/libc/src/include/internal/bindings/bindings.rs
            
            - name: Check format
              run: |
                    FMT_CHECK=1 make fmt
