name: Rust format check

on: [push, pull_request]

jobs:
    fmt:
        name: Rustfmt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - name: Cache toolchain
              id: cache-toolchain
              uses: actions/cache@v3
              env:
                  cache-name: cache-toolchain
              with:
                path: |
                  ~/.cargo
                  ~/.rustup
                  ~/.bashrc
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('.github/workflows/rustfmt.yml') }}
          
            - if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
              name: Install nightly-2023-01-21
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly-2023-01-21
                  override: true
                  components: rustfmt, clippy
            
            - name: Check format
              uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: --all -- --check
